[workspace]
members = ["sett", "matlab"]
default-members = ["sett"]

[workspace.dependencies]
config = { version = "0.13.3", features = ["json", "yaml", "toml"] }

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
