[package]
name = "sett-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
na = { package="nalgebra", version="0.31.4" }
ode_solvers = "0.3.7"
