name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Gather cached dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Run cargo check
        run: cargo check

  lints:
    name: Lints
    runs-on: ubuntu-latest
    needs: [check]
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: clippy, rustfmt
      
      - name: Gather cached dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [check]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Gather cached dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
